### ISSUE TITLE
重庆新桥医院有什么问题？

### ISSUE THREAD

**Issue by heretreeli** [langhua9527/BlackheartedHospital#1]
重庆新桥医院有什么问题？

**Comment by langhua9527** [comment]
你好，这里无法判断这家医院有什么问题，但是你可以通过以下方法来识别
1.查看医院的网站，或者某些关键词是否在百度进行了推广。
2.浏览医院的网站，正常的网站一般进去就不会让你有想看的想法，有些医院的网站进去写在什么24小时在线询咨，专家在线，包治百病的什么的.
以上的方法也不是绝对的
