### ISSUE TITLE
排序建议

### ISSUE THREAD

**Issue by chenshaoju** [langhua9527/BlackheartedHospital#26]
你好：
　　我注意到列表中排序比较诡异，比如我想看长沙的所有医院，但是却分成了好几段，其中还有重复的（比如长沙博大泌尿专科医院）。

　　能否按照特定格式整理一下，比如：

城市：
医院名　（系名（莆田系etc...））

　　谢谢。

**Comment by langhua9527** [comment]
你就只看 1.2 beta 的内容吧，是分好的，前面的，你就Ctrl+F 搜长沙吧
