### ISSUE TITLE
张家港属于苏州地区

### ISSUE THREAD

**Issue by winsweet** [langhua9527/BlackheartedHospital#40]
苏州市下辖的县级市有昆山,太仓,常熟,张家港....下面的这两条可以合并起来

#苏州

苏州东吴医院
苏州华美美莱整形医院
昆山虹桥医院
常熟东方妇科医院
常熟仁爱医院
昆山阳光医院
苏州圣爱医院
苏州新医科

#张家港

张家港朝阳五官科医院

**Comment by langhua9527** [comment]
已有人提交修改
