### ISSUE TITLE
毫无根据，毫无意义，哗众取宠，丢人现眼！

### ISSUE THREAD

**Issue by wsdjeg** [langhua9527/BlackheartedHospital#70]
1. 没有任何事实依据，可能部分医院有问题，但绝不是全部！
2. 没有任何意义，纯粹哗众取宠，吸引star
3. 这样的仓库居然上github榜，丢人现眼，丢中国人脸，更丢中国程序员脸！！！

**Comment by ylc395** [comment]
有你这样的才丢中国人的脸

**Comment by wsdjeg** [comment]
@ylc395 你懂个屁,知道前几次github被墙,是谁救了github么?迟早变成第二个谷歌.好东西,你们不懂得珍惜,不好好用,闲撤这些网上乱七八糟的,你敢百分百确认网上这些是事实?

**Comment by luckypoem** [comment]
@wsdjeg 你个傻逼。幸亏不是所有程序员都像你这么傻逼。你tmd才是丢尽中国程序员的脸

**Comment by wsdjeg** [comment]
@luckypoem 滚尼吗比, 你懂个屁, github上面是你们谈论政治的吗, 现在gist google faceboke tw都被墙了,你要github也被墙. 真2比一个 block

**Comment by ylc395** [comment]
> github上面是你们谈论政治的吗

揭露黑医院也算政治啦

**Comment by wangqiliang** [comment]
@ylc395 很抱歉，如果毫无依据空穴来风的所谓医院信息，我想他们应该不会去收集的。
何况这么做与编程随想的zhao那个repo（谈论政治被451了）有本质区别。
