### ISSUE TITLE
不会再救github第二次！

### ISSUE THREAD

**Issue by wsdjeg** [langhua9527/BlackheartedHospital#71]
正如ruby china管理员所说，他们救了github两次了，但是如果任然有人如此在github上讨论社会问题，迟早会被和谐！！成为下一个google

**Comment by ToyYan** [comment]
用得着害怕么，上github的估计没有几个不会翻墙的吧？

**Comment by tim-hub** [comment]
这也不算政治事件吧？

**Comment by YiuTerran** [comment]
真是滑稽，为什么不能讨论，已block楼主。

**Comment by wsdjeg** [comment]
你了解多少事实？你有什么资本讨论？

**Comment by wsdjeg** [comment]
继续自作孽吧

**Comment by xiao-hu00** [comment]
sb

**Comment by luckypoem** [comment]
@wsdjeg 你个傻逼。幸亏不是所有程序员都像你这么傻逼。你tmd才是丢尽中国程序员的脸。
又见到一个傻逼。

**Comment by excelle08** [comment]
这又不是政治敏感，如果github会因为这个被墙那才说明天朝真的败絮其中到了极点了，这种想法真的就是斯德哥尔摩综合征。假设你不是莆田系利益相关的人。

**Comment by wbinary** [comment]
唉，自以为是的家伙，王世东
