### ISSUE TITLE
别哗众取宠了行吗？

### ISSUE THREAD

**Issue by broven** [langhua9527/BlackheartedHospital#73]
依据在哪里？一个网传解决所有是否真实的疑问？    丢脸都丢到国外去了，github再这样也快被墙了

**Comment by wsdjeg** [comment]
你看看我的两个issue.我自己close了，自作孽呀，这是

**Comment by everhopingandwaiting** [comment]
关 git 毛事!!  @broven

**Comment by ylc395** [comment]
> git再这样也快被墙了

git、github傻傻分不清楚

**Comment by wsdjeg** [comment]
@ylc395 也就你才会觉得别人分不清楚.
