### ISSUE TITLE
上海五官科医院是吗? 

### ISSUE THREAD

**Issue by childe** [langhua9527/BlackheartedHospital#8]
我搜索出来的是复旦附属医院

**Comment by langhua9527** [comment]
数据来据凤凰网,凤凰网的数据又来自于一家专业机构

**Comment by kuyeluofan** [comment]
复旦大学附属眼耳鼻喉科医院是真的好医院，大家俗称五官科医院，官网是http://www.fdeent.org/
这里说的上海五官科医院应该指的是利用这个不正式的名字来行骗的 上海复大五官科医院之流。

**Comment by chaoxn** [comment]
五官科医院和复旦附属耳鼻喉医院就是一家，算是上海最好的五官科医院了，去年去看了耳朵，今年看了眼睛

**Comment by bzhu5** [comment]
建议在每个有类似误解的冒牌医院后注明正版医院的名字。

**Comment by HorseLuke** [comment]
@langhua9527 凤凰网的真正来源可能是13年的“莆田系医疗领袖名录”，个人觉得可信度不高：http://www.ptfish.com/thread-731956-1-1.html

**Comment by ibelem** [comment]
果然有人和我有一样的疑问。

https://zh.wikipedia.org/wiki/%E8%8E%86%E7%94%B0%E7%B3%BB 这里也提到了上海五官科医院。

一直惊诧上海市五官科医院怎么可能是莆田系, 应该说的是上海沪申五官科医院吧? 但莆田系名单除了上海沪申五官科医院又单列了上海五官科医院, 晕了. 又有人说上海五官科医院是莆田系，上海市五官科医院是正牌，有点晕，毕竟 http://www.fdeent.org 官网是这么写的 <title>复旦大学附属眼耳鼻喉科医院/上海五官科医院</title> .

**Comment by langhua9527** [comment]
已经修改成为 上海沪申五官科医院

**Comment by ibelem** [comment]
@langhua9527 按照 http://weibo.com/1845864154/DtMPb7QSw?type=comment#_rnd1462254604013 的说法，伪劣的上海五官科医院也是存在的，是否不应该删除而应该提醒大家注意和 复旦大学附属眼耳鼻喉科医院/上海五官科医院 进行区分？

> 被列入莆田系的那家医院名称就叫“上海五官科医院！”隶属深圳博爱医疗集团

**Comment by cxz1998** [comment]
建议在各种可能存在误导的地方建立备注，如山寨货“上海五官科医院”旁边备注上“山寨上海市五官科医院，全名复旦大学附属眼耳鼻喉科医院”

**Comment by jincdream** [comment]
同学们直接提备注的pull request嘛~
