### ISSUE TITLE
该如何正视莆田系相关事件

### ISSUE THREAD

**Issue by wsdjeg** [langhua9527/BlackheartedHospital#93]
一帮傻乎乎的人,这个仓库ID明显新建了这个repo,才搞的jingoal.com 组织,明显就是吸引眼球的,一个个还凑着脸贴上去

**Comment by langhua9527** [comment]
本人保证，维护这个项目，不会有任何的商业目的，过去不会有，将来也不会有，请大家监督。
希望你能有正常的心态来看待这个工程，你所以说的每一句话，在将来都是搜索的到的。
也请你不要以你自己心态来衡量别人是怎么想的。

**Comment by xiaolongyuan** [comment]
创建个组织 来维护吧 省的嫌疑

**Comment by zhuangbiaowei** [comment]
@langhua9527 这种issue，关闭了就是。何必理睬这种喷子？

**Comment by wsdjeg** [comment]
@langhua9527 不是我以个人心态来看这个项目,请问你读过
http://chloerei.com/2014/02/24/we-saved-github-twice/

**Comment by SaltfishAmi** [comment]
恕我眼拙，请告诉我哪里有jingoal.com

**Comment by wsdjeg** [comment]
@zhuangbiaowei 无知,请看完我发的链接再说

**Comment by wsdjeg** [comment]
@SaltfishAmi 自己看作者org,新建这仓库之前是没有的

**Comment by wsdjeg** [comment]
@langhua9527 牛,组织都退了

**Comment by wsdjeg** [comment]
https://github.com/Jingoal
我没有来得及给你截图.

**Comment by xiaolongyuan** [comment]
还是不明白什么意思

**Comment by zhuangbiaowei** [comment]
@langhua9527 建议尽快ban掉@wsdjeg 项目中不需要这种人出现。

**Comment by wsdjeg** [comment]
@xiaolongyuan 这个仓库的作者,利用网络上的这些信息,吸引用户,在新建这个仓库之前,并没有加入jingoal组织,后来加入的,我提出这个issue他就把组织给退了,开一个马甲小号来问我哪里有jingoal.com.

**Comment by wsdjeg** [comment]
@zhuangbiaowei 不明白,为什么你会意见如此大,难道你觉得这样发表这个项目是合理的?

**Comment by xiaolongyuan** [comment]
办了事 成功吸引大家关注这件事 没有虚假恶意的中伤  有何不可 至于组织 发起者已经退出了  我建议应把此项目新建个其他组织托管

**Comment by wsdjeg** [comment]
@zhuangbiaowei 看了你的blog http://www.zhuangbiaowei.com/blog/
觉得你至少应该是有思想的人,为何做出如此不明智的举措,github如果被墙,该多可惜

**Comment by xiaolongyuan** [comment]
不谈政治 不谈政治 不谈政治

**Comment by langhua9527** [comment]
jingoal的组织是我去年加入的，去年已经离职，但是离职并没有退出github，为了避免大家以为有商业目的，刚刚就退出了

**Comment by wsdjeg** [comment]
@xiaolongyuan 我想问问,我之前发的链接,拯救github2次的链接,你是否看了,难道你觉得这个项目这样对github来说,是合理的吗?而且,网上收集到的这些信息,谁敢证明?至少我了解的几个其中的医院,并没有这些事情

**Comment by zhuangbiaowei** [comment]
@wsdjeg 当然合理。你如果不赞同，请离开即可。我看到你开了好些issue，指责谩骂，毫无贡献。
如果你看过我的更多的blog，应该会看到这篇：《程序员与政治》

http://www.zhuangbiaowei.com/blog/?p=559

**Comment by wsdjeg** [comment]
@zhuangbiaowei 那我想问问,这些信息,你能够百分百确认吗?

**Comment by xiaolongyuan** [comment]
@wsdjeg 我看了 所以不是无脑喷 不是圣母婊 
![image](https://cloud.githubusercontent.com/assets/3142363/14989404/3bfefa06-118a-11e6-9913-f29f7b60c8de.png)

**Comment by chai2010** [comment]
@wsdjeg 真没必要担心github是否会被墙，该墙的始终会被墙。
这个项目确实可能有你才想某些目的，但这是每个github用户的权利。
你也可以搞一个，来宣传你的观点

**Comment by zhuangbiaowei** [comment]
@wsdjeg 咱们可以接着聊聊。一个公开的项目，所有的内容，修订的过程，issue的讨论，全部都是公开的。而且正在飞快的演进过程中。这正是开源项目的活力所在。

一个真正活力的开源项目，从来不会宣称自己毫无bug，但是却会欢迎所有的参与者一起来改进完善。

如果这些信息，无法百分之百的确认，就去查证，去追索，去修订。这才是积极正面的做事之道。

**Comment by wsdjeg** [comment]
@chai2010 其实一开始,我也很合理在说,但刚发issue就被喷,我也很火大,

**Comment by xiaolongyuan** [comment]
我也提了pr 的 虽然不敢说百分百 至少我提供的信息注明了来源

**Comment by zhuangbiaowei** [comment]
@xiaolongyuan  me too

**Comment by xiaolongyuan** [comment]
这件事我觉得每个人 不仅是我们程序员圈子 Action !
想想我们周围的七大姑八大姨

**Comment by wsdjeg** [comment]
@xiaolongyuan 我觉得 这个项目名称是黑心医院,当涉及到任何一个医院名称的时候,起码有一个确切的事件,而不是因为一件事情,将所有这类医院都一棒子打死

**Comment by zhuangbiaowei** [comment]
@wsdjeg 呵呵，那么你断然认为这个项目是为了宣传Jingoal.com呢？

**Comment by wsdjeg** [comment]
@zhuangbiaowei 最后,我只想说一句,不是所有莆田系的医院都属于黑心医院,不要把网上有心人发的信息误解了.
因为5.1号这个项目新建时候 作者没有加组织,昨天也没有,今天加了, 也退了,虽然我没有截图,我也不需要你相信

**Comment by xiaolongyuan** [comment]
@wsdjeg 这是一个问题 
如此之事，现实生活中虽略有见闻或耳闻 但如此规模与组织 实在骇人听闻  所以我觉得 从出发点来说 并没有什么 有错误或遗漏 可以补充
# 再说 错杀一个 总比害人一片好的多

**Comment by langhua9527** [comment]
@wsdjeg 有反对的意见很好，希望你继续监督，也希望你能找到工程里面更多的问题来，我会及时修改，与其在这里争论，你不如去找找工程里面有问题的地方，比如说有的程序员提出上海五官科那个医院有问题，后来不是解决了啥

**Comment by zhuangbiaowei** [comment]
平心而论：所有莆田系的医院都属于黑心医院。的确是一个过度的指责！

不过，告诉老百姓，哪些医院属于莆田系，也是知情权的一种吧？

你明知他是莆田系，还很有信心的进去看病，我当然不会拦着。

**Comment by wsdjeg** [comment]
@xiaolongyuan 我的工作就是跟医院打交道,我了解医院的事情 比你们都多,医院不是你们想象的那么恶心,也有很实实在在的.当然,会有非常势力的医生,但是知道为什么在中国医患关系这么差,有一个检验科主任跟我说,这是老百姓在自作孽

**Comment by zhuangbiaowei** [comment]
@wsdjeg 所以，你因为一个检验科主任的论断，就认为“都是老百姓自作孽”？

呵呵

**Comment by wsdjeg** [comment]
那么就是医生在造孽咯? 你觉得呢?

**Comment by xiaolongyuan** [comment]
@wsdjeg  我相信正规医院的医生

**Comment by HorseLuke** [comment]
@xiaolongyuan ，医院错杀一个容易导致医患纠纷。

另外一个，是我一直在好几个地方提过的，凤凰的名单本身就存在不可信问题，其实就可以向相关机构投诉为不实新闻。而现在的情况就是，媒体把大家当枪使，大家还乐意卖命，而且最有意思的是，还是最喜欢自由的程序员。

**Comment by xiaolongyuan** [comment]
但不可否认 医患关系 并不简简单是医生、患者某一方面的问题 更深层次还有医疗zd ...

**Comment by wsdjeg** [comment]
近期 医院发生的事情你了解多少,江浙这边被抓起来的医院的人,因为什么事情,我们都清清楚楚.国家放着临床医生不管,因为一些鸡毛蒜皮事情,在抓后勤人员,我只想说,这样的体制,也到头了.
医院一切罪恶根源,都是在临床,一切开药,检查,手术单子都是临床开的.医院一切收费来源与临床

**Comment by zhuangbiaowei** [comment]
@wsdjeg 我相信，世界很复杂，有好医生，有坏医生。有胡搅蛮缠的病人，也有通情达理的病人。

简简单单，只从一种立场看问题，其实相当simple。

**Comment by wsdjeg** [comment]
总是点到close,感觉github不想让我说了.

**Comment by xiaolongyuan** [comment]
@zhuangbiaowei  +1 但这是另一说了

**Comment by HorseLuke** [comment]
@wsdjeg 医患关系的问题是多方面的，医生认为病人有问题，病人认为医生有问题。每个人的角度都有偏倚~

**Comment by xiaolongyuan** [comment]
我感到 高层对这方面肯定是要管了 目前最多算第一波 好戏还在后头

**Comment by wsdjeg** [comment]
@xiaolongyuan 近几个月,动荡最大的不是民营医院,公立医院变动才大.

**Comment by xiaolongyuan** [comment]
仗着现在国家医保 随便一下几千块 还瞧不出名堂。。。
